feat: hardhat erc721
hedera-dev/hedera-tokens pull request #2
Opened 2024-01-30 07:33 UTC by bguiz

## What

- Add a new hardhat project
- Imports ERC721 implementation from OZ

## Why

- Demo use of non-fungible tokens using a pure HSCS implementation (no HTS)
- Demo use of deployment to Hedera Testnet + verification via Sourcify

2024-02-06 19:15 UTC, a-ridley commented on erc721-hardhat/README.md
> +This project has been designed as a minimal example demonstration;
I suggest adding the files necessary to update in order to get this project running. 

For example, rename the .env.example to .env and configure your env. variables which will be used in hardhat.config.cjs file. Just something to guide the user to which files need configuring

2024-02-06 19:38 UTC, a-ridley requested changes
Adding a bit more guidance on what is needed to get this running upfront will help. 

In addition, lets try to figure out why npx mnemonics is giving that issue or how to work around it :)

2024-02-07 07:39 UTC, bguiz commented on erc721-hardhat/README.md
> +This project has been designed as a minimal example demonstration;
OK added instructions for the `.env` file

2024-02-07 07:39 UTC, bguiz commented on erc721-hardhat/README.md
> +npm run compile
Yup, need an `npm i` command prior to this

2024-02-07 07:39 UTC, bguiz commented on erc721-hardhat/hardhat.config.cjs
> +npx mnemonics@1.1.3
I think this needs NodeJs v20 at minimum to proceed, I'll add that

2024-02-07 20:04 UTC, a-ridley commented on erc721-hardhat/README.md
> +npm run deploy
I get the following error

```
> erc20-hardhat-demo@0.0.0 deploy
> npm run deploy:hederatestnet


> erc20-hardhat-demo@0.0.0 deploy:hederatestnet
> npx hardhat run --network hederatestnet scripts/deploy.js

https://pool.arkhia.io/hedera/testnet/json-rpc/v1/922......
Deploying...

/Users/abi/Dev/hedera-dev-repos/hedera-tokens/erc721-hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:88
      const error = new ProviderError(
                    ^
ProviderError: [Request ID: 97d65a37-c521-4bed-b8b5-1d6c4b3769a2] Requested resource not found. address '0x38585566fb010606240194578cb3e4Ee44637D93'.
    at HttpProvider.request (/Users/abi/Dev/hedera-dev-repos/hedera-tokens/erc721-hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HardhatEthersSigner.sendTransaction (/Users/abi/Dev/hedera-dev-repos/hedera-tokens/erc721-hardhat/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at ContractFactory.deploy (/Users/abi/Dev/hedera-dev-repos/hedera-tokens/erc721-hardhat/node_modules/ethers/src.ts/contract/factory.ts:111:24)
    at main (file:///Users/abi/Dev/hedera-dev-repos/hedera-tokens/erc721-hardhat/scripts/deploy.js:10:29)

```

2024-02-09 02:09 UTC, a-ridley approved these changes
LGTM!

love that you add a clean command and description of error and what to do :)

2024-02-09 02:10 UTC, merged